steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/tribal-cortex-428712-n1/kubernetes/container2-image:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/tribal-cortex-428712-n1/kubernetes/container2-image:latest'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/deployment.yaml'
    env:
      - 'BUILD_ID=$BUILD_ID'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './kubernetes/service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

images:
  - 'us-central1-docker.pkg.dev/tribal-cortex-428712-n1/kubernetes/container2-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY
