apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kubernetes-deployment1"
  namespace: "default"
  labels:
    app: "kubernetes-deployment1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kubernetes-deployment1"
  template:
    metadata:
      labels:
        app: "kubernetes-deployment1"
    spec:
      containers:
      - name: "container2"
        image: "us-central1-docker.pkg.dev/tribal-cortex-428712-n1/kubernetes/container2-image:latest"
        imagePullPolicy: Always  # Specify the image pull policy here
        volumeMounts:
          - mountPath: /home/nikulpokukadiya1998
            name: kubernetes-volume1
      priorityClassName: high-priority
      volumes:
        - name: kubernetes-volume1
          persistentVolumeClaim:
            claimName: kubernetes-volume-claim1
