apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service1
spec:
  selector:
    app: kubernetes-deployment1
  ports:
    - name: microservice-port2
      protocol: TCP
      port: 80
      targetPort: 6001
  type: LoadBalancer
