apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service1
spec:
  selector:
    app: kubernetes-deployment
  ports:
    - name: microservice-port
      protocol: TCP
      port: 80
      targetPort: 6000
    - name: microservice-port2
      protocol: TCP
      port: 6001
      targetPort: 6001
  type: LoadBalancer
